language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: false
      osx_image: xcode7.3

services:
  - docker

addons:
  apt:
    packages:
      - clang-format-3.9
      - p7zip-full

install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"

deploy:
  provider: releases
  api_key:
    secure: "lfOXGtH+Pq6bOoMX9gC2QroVluy6ZaQYVc+fNcO6LCnt5xCQbsg1Rwmb8ew/gEVhmHfssG9W90tI2NyubA7FA2RyZNPkHTNCcO+M/GSHpeivBYVP/GzmDF6dgeo96r4H0E09/shooC1JYrLEmc5pxCdsMAOguLab0pX09cA94nFJNzKOhfzratI3vl3/ekn/HH+kRgmhFWGkMg+7qcTPW8onSX6wTJS3+jh3RyclzvKJRAAGCi3ZDuEezHrSbiW0y53BwjZMD606PB15O26nimzJHzco8B6nsjngbz91az4EaKs7iefCVMAAAKKNXk+ntNQxHfASt7RanDlGwGrBz15OKKPKs1n46fauE6lC9c/it8b5gZR+Rv67jDY2eRR32PRkEy5KWnksIjhSimqG9TLcLbbD78LYSaUwdV1RFnSzrZrMVj1/yhtiZN/tKreFVCDsr8irVjgdpOmkOVRLrYTDu+EoIgsOGybEfU1C8l8MwFEj4IpX7VqILIsJgFiwRQI4ThgOKWiYmQL/bcnUtyn9yUjPvKfvhJ6yGKddZk7yTv9jj1823P8FDqcPJdNoRNsrwuk1ebRpchatG7Kyyur9hLRJT2hswuDzC003svhFRjFbzW0qyucSmgIrwuuCAshxhDY6WKC3pYk5BRsD70A1xGmqkhixUTpULkmqTWM="
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
